# Generated by Django 6.0.1 on 2026-03-19 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Voter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.TextField()),
                ('first_name', models.TextField()),
                ('street_num', models.IntegerField()),
                ('street_name', models.TextField()),
                ('apt_num', models.IntegerField()),
                ('zip', models.IntegerField()),
                ('date_of_birth', models.DateField()),
                ('reg_date', models.DateField()),
                ('party', models.CharField(max_length=2)),
                ('prec_num', models.IntegerField()),
                ('v20', models.BooleanField()),
                ('v21t', models.BooleanField()),
                ('v21p', models.BooleanField()),
                ('v22', models.BooleanField()),
                ('v23', models.BooleanField()),
                ('score', models.IntegerField()),
            ],
        ),
    ]
