# Generated by Django 6.0.1 on 2026-03-19 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voter_analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='apt_num',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
