# Generated by Django 6.0.1 on 2026-03-19 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voter_analytics', '0002_alter_voter_apt_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='voter',
            name='reg_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
