# Generated by Django 6.0.1 on 2026-03-19 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voter_analytics', '0003_alter_voter_date_of_birth_alter_voter_reg_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='prec_num',
            field=models.CharField(),
        ),
    ]
