# Generated by Django 6.0.1 on 2026-02-12 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mini_insta', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='ursername',
            new_name='username',
        ),
    ]
