# Generated by Django 6.0.1 on 2026-04-15 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='type',
        ),
        migrations.RemoveField(
            model_name='lodging',
            name='type',
        ),
        migrations.RemoveField(
            model_name='transportation',
            name='type',
        ),
    ]
