# Generated by Django 6.0.1 on 2026-04-17 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_remove_activity_type_remove_lodging_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='caption',
            field=models.TextField(blank=True),
        ),
    ]
