# Generated by Django 6.0.1 on 2026-04-17 03:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_media_caption'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.TextField()),
                ('item', models.TextField()),
                ('isPacked', models.BooleanField(default=False)),
                ('adventure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.adventure')),
            ],
        ),
    ]
