# Generated by Django 6.0.1 on 2026-04-17 03:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_packingitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='packingitem',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
