# Generated by Django 6.0.1 on 2026-04-17 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_packingitem_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='packingitem',
            name='notes',
            field=models.TextField(default='before'),
            preserve_default=False,
        ),
    ]
