# Generated by Django 6.0.1 on 2026-04-17 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_packingitem_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transportation',
            name='travel_type',
            field=models.CharField(choices=[('bus', 'Bus'), ('taxi', 'Taxi'), ('uber', 'Uber'), ('car', 'Car'), ('flight', 'Flight'), ('train', 'Train'), ('ferry', 'Ferry'), ('other', 'Other')], max_length=20),
        ),
    ]
