# Generated by Django 6.0.1 on 2026-04-18 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_alter_transportation_travel_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packingitem',
            name='item_type',
            field=models.CharField(choices=[('clothing', 'Clothing'), ('toiletries', 'Toiletries'), ('miscellaneous', 'Miscellaneous'), ('electronics', 'Electronics'), ('beauty', 'Beauty'), ('health + self care', 'Health + Self Care'), ('trip specific', 'Trip Specific'), ('other', 'Other')], max_length=20),
        ),
    ]
