# Generated by Django 6.0.4 on 2026-04-28 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_activity_timestamp_lodging_timestamp_media_timestamp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packingitem',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
